-- public 스키마 테이블 복구 명령어

-- 1. ads_data 테이블 생성
CREATE TABLE IF NOT EXISTS public.ads_data (
  tenant_id uuid NOT NULL,
  date date NOT NULL,
  channel text NOT NULL,
  campaign_id text,
  campaign_name text,
  ad_group_id text,
  ad_group_name text,
  ad_id text,
  ad_name text,
  ad_type text,
  keyword text,
  placement text,
  device_type text,
  country text,
  region text,
  age_group text,
  gender text,
  budget_amount numeric,
  bid_strategy text,
  bid_amount numeric,
  quality_score integer,
  impressions bigint,
  clicks bigint,
  conversions bigint,
  conversion_value numeric,
  cost numeric,
  spend numeric,
  revenue numeric,
  ctr numeric,
  cpc numeric,
  cpm numeric,
  cpa numeric,
  roas numeric,
  roi numeric,
  conversion_rate numeric,
  bounce_rate numeric,
  session_duration numeric,
  new_users integer,
  returning_users integer,
  video_views integer,
  video_completion_rate numeric,
  video_engagement_rate numeric,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  id bigint NOT NULL DEFAULT nextval('ads_data_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ads_data_pkey PRIMARY KEY (id)
);

-- 2. cafe24_products 테이블 생성
CREATE TABLE IF NOT EXISTS public.cafe24_products (
  tenant_id uuid NOT NULL,
  product_code text NOT NULL,
  product_name text NOT NULL,
  category text,
  price numeric,
  stock_quantity integer,
  color text,
  size text,
  id bigint NOT NULL DEFAULT nextval('cafe24_products_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cafe24_products_pkey PRIMARY KEY (id)
);

-- 3. fact_sales 테이블 생성
CREATE TABLE IF NOT EXISTS public.fact_sales (
  order_id text,
  customer_id text,
  customer_name text,
  customer_email text,
  customer_phone text,
  customer_grade text,
  order_status text,
  payment_method text,
  shipping_fee numeric,
  discount_amount numeric,
  total_amount numeric,
  unit_price numeric,
  cost_price numeric,
  margin numeric,
  margin_rate numeric,
  brand text,
  product_code text,
  option_info text,
  weight numeric,
  dimensions jsonb,
  tags ARRAY,
  is_new_customer boolean,
  is_returning_customer boolean,
  order_hour integer,
  order_day_of_week integer,
  order_month integer,
  order_quarter integer,
  order_year integer,
  is_weekend boolean,
  is_holiday boolean,
  season text,
  weather_condition text,
  temperature_min numeric,
  temperature_max numeric,
  humidity numeric,
  precipitation numeric,
  wind_speed numeric,
  campaign_id text,
  campaign_name text,
  ad_group_id text,
  keyword text,
  impressions integer,
  clicks integer,
  conversions integer,
  ctr numeric,
  cpc numeric,
  cpa numeric,
  roas numeric,
  source text,
  medium text,
  referrer text,
  device_type text,
  browser text,
  os text,
  screen_resolution text,
  country text,
  city text,
  postal_code text,
  shipping_address jsonb,
  billing_address jsonb,
  notes text,
  tags_custom ARRAY,
  is_gift boolean,
  gift_message text,
  is_bulk_order boolean,
  bulk_discount_rate numeric,
  loyalty_points_earned integer,
  loyalty_points_used integer,
  coupon_code text,
  coupon_discount numeric,
  affiliate_id text,
  affiliate_commission numeric,
  return_reason text,
  return_date date,
  refund_amount numeric,
  refund_reason text,
  refund_date date,
  review_rating integer,
  review_comment text,
  review_date date,
  is_reviewed boolean,
  is_recommended boolean,
  social_share_count integer,
  wishlist_count integer,
  cart_abandonment_reason text,
  time_to_purchase integer,
  page_views integer,
  session_duration integer,
  bounce_rate numeric,
  exit_page text,
  entry_page text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  ga_client_id text,
  ga_session_id text,
  ga_user_id text,
  fb_pixel_id text,
  fb_conversion_id text,
  naver_pixel_id text,
  kakao_pixel_id text,
  custom_attributes jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  tenant_id uuid NOT NULL,
  sale_date date NOT NULL,
  region text,
  channel text,
  category text,
  sku text,
  product_name text,
  color text,
  size text,
  qty numeric,
  revenue numeric,
  ad_cost numeric,
  discount_rate numeric,
  tavg numeric,
  id bigint NOT NULL DEFAULT nextval('fact_sales_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  file_id uuid,
  row_num integer,
  original_data jsonb,
  CONSTRAINT fact_sales_pkey PRIMARY KEY (id)
);

-- 4. tenants 테이블 생성
CREATE TABLE IF NOT EXISTS public.tenants (
  name text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);

-- 5. upload_logs 테이블 생성
CREATE TABLE IF NOT EXISTS public.upload_logs (
  tenant_id uuid NOT NULL,
  file_name text NOT NULL,
  file_size bigint,
  total_rows integer NOT NULL,
  error_message text,
  reset_time timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  upload_time timestamp with time zone DEFAULT now(),
  inserted_rows integer NOT NULL DEFAULT 0,
  skipped_rows integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'processing'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT upload_logs_pkey PRIMARY KEY (id)
);

-- 6. weather_data 테이블 생성
CREATE TABLE IF NOT EXISTS public.weather_data (
  date date NOT NULL,
  region character varying NOT NULL,
  temperature numeric,
  humidity integer,
  precipitation numeric,
  description character varying,
  id integer NOT NULL DEFAULT nextval('weather_data_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weather_data_pkey PRIMARY KEY (id)
);

-- 시퀀스 생성 (필요한 경우)
CREATE SEQUENCE IF NOT EXISTS ads_data_id_seq;
CREATE SEQUENCE IF NOT EXISTS cafe24_products_id_seq;
CREATE SEQUENCE IF NOT EXISTS fact_sales_id_seq;
CREATE SEQUENCE IF NOT EXISTS weather_data_id_seq;

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_fact_sales_tenant_date ON public.fact_sales(tenant_id, sale_date);
CREATE INDEX IF NOT EXISTS idx_fact_sales_sku ON public.fact_sales(sku);
CREATE INDEX IF NOT EXISTS idx_ads_data_tenant_date ON public.ads_data(tenant_id, date);
CREATE INDEX IF NOT EXISTS idx_cafe24_products_tenant ON public.cafe24_products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_weather_data_region_date ON public.weather_data(region, date);
