name = "joogo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 설정
pages_build_output_dir = "apps/web-admin/.next"

[env.production]
name = "joogo-prod"

[env.preview]
name = "joogo-preview"
