name = "joogo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "3c9a7e5abdcef2bba6746bd305f11ede"

# Pages 설정
pages_build_output_dir = "apps/web-admin/.next"

[env.production]
name = "joogo-prod"

[env.staging]
name = "joogo-staging"

# Cloudflare Pages + Edge Functions 설정
[build]
command = "pnpm build"
cwd = "apps/web-admin"
