name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript check
        run: pnpm -F @joogo/web-admin typecheck
        
      - name: Prepare env for CI
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=" > apps/web-admin/.env.local
          echo "SUPABASE_SERVICE_ROLE_KEY=" >> apps/web-admin/.env.local
          echo "OPENAI_API_KEY=" >> apps/web-admin/.env.local
          echo "TENANT_ID_DEFAULT=default" >> apps/web-admin/.env.local
          echo "NEXT_PUBLIC_DATA_SOURCE=mock" >> apps/web-admin/.env.local
          echo "KMA_SERVICE_KEY=" >> apps/web-admin/.env.local
          echo "KMA_BASE_URL=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0" >> apps/web-admin/.env.local
        
      - name: Build (Cloudflare Next)
        working-directory: apps/web-admin
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || '' }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || '' }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
        run: |
          node -e "console.log('has url?', !!process.env.NEXT_PUBLIC_SUPABASE_URL, 'has key?', !!process.env.SUPABASE_SERVICE_ROLE_KEY)"
          pnpm dlx @cloudflare/next-on-pages@1

      - name: Deploy to Cloudflare Pages (wrangler CLI)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN || '' }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || '' }}
        run: |
          npx wrangler@4.35.0 pages deploy \
            apps/web-admin/.vercel/output/static \
            --project-name=joogo \
            --branch="${{ github.ref_name }}"
