name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript check
        run: pnpm -w tsc --noEmit
        
      - name: Prepare env for CI
        run: cp apps/web-admin/.env.ci apps/web-admin/.env.local
        
      - name: Build web-admin (Cloudflare Next)
        working-directory: apps/web-admin
        run: npx -y @cloudflare/next-on-pages@latest
        
      - name: Check output
        run: |
          ls -la apps/web-admin/.vercel/output/static
          ls -la apps/web-admin/.vercel/output/functions || true
        
      - name: Deploy to Cloudflare Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npx wrangler@4.35.0 pages deploy apps/web-admin/.vercel/output/static \
            --project-name=joogo \
            --branch=${{ github.ref_name }} \
            --compatibility-date=2024-01-01
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
